package com.sample.system.card.service.domain.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * CardStatus Value Object
 * Represents the possible states of a card
 * Following DDD principles for value objects
 */
@Getter
@RequiredArgsConstructor
public enum CardProfileStatus implements CodedEnum {
    ACTIVE(1, "فعال"),
    INACTIVE(2,"غیرفعال"),
    BLOCKED(3,"مسدود"),
    EXPIRED(4,"منقضی شده"),
    PENDING(5,"درانتظار"),
    SUSPENDED(6,"معلق");

    private final Integer code;
    private final String description;

    // Constructor and getter are automatically generated by Lombok annotations

    /**
     * Check if card can be blocked
     */
    public boolean canBeBlocked() {
        return this == ACTIVE;
    }

    /**
     * Check if card is in a terminal state
     */
    public boolean isTerminalState() {
        return this == EXPIRED || this == BLOCKED;
    }
}
