
# Application
server.port=${CARD_SERVER_PORT:8007}
spring.application.name=card-service

# Datasource
spring.datasource.url=${CARD_DATASOURCE_URL:}
spring.datasource.username=${CARD_DATASOURCE_USERNAME:card}
spring.datasource.password=${CARD_DATASOURCE_PASSWORD:uWAEneXYEe6LLPDy4qPx}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Envers
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.envers.audit_table_suffix=_AUD
spring.jpa.properties.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.hibernate.envers.revision_field_name=rev
spring.jpa.properties.hibernate.envers.revision_type_field_name=revtype
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Flyway
spring.flyway.enabled=false
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.validate-on-migrate=false
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.schemas=CARD
spring.flyway.locations=classpath:db/migration
spring.flyway.out-of-order=false
spring.flyway.group=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka-server-svc.dragon.svc.cluster.local/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator / Management
management.endpoints.web.exposure.include=health,info
management.info.enabled=true
management.info.app.name=Card Service
management.info.app.version=1.0.0
management.info.app.description=This is card service API

# File Storage
file.storage.path=${CARD_FILE_STORAGE_PATH:uploads/}

# SSM Client
ssm.base.url=${SSM_BASE_URL:}
ssm.response.decrypt.key=${SSM_DECRYPT_KEY:}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.api-docs.path=/v3/api-docs

swagger.oauth.token-url=${uaa.client.base-url}${uaa.client.token-path}
swagger.oauth.client-id=${uaa.client.client-id:card-service}
swagger.oauth.client-secret=${uaa.client.client-secret:card_client_secret}

uaa.client.base-url=https://stage-sbu-panel.bmicc.ir
uaa.client.token-path=/oauth2/token
uaa.client.client-id=card-service
uaa.client.client-secret=card_client_secret
uaa.client.scope=
uaa.client.jwk-set-uri=https://stage-sbu-panel.bmicc.ir/oauth2/jwks
uaa.client.public-paths=/actuator/health,/actuator/info,/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**,/swagger-resources/**,/webjars/**
uaa.client.access-control-enabled=false

spring.data.redis.host=${CARD_REDIS_HOST:redis-svc.redis.svc.cluster.local}
spring.data.redis.port=${CARD_REDIS_PORT:6379}
spring.data.redis.password=${CARD_REDIS_PASSWORD:a@123456}
redisson.singleServerConfig.address=${CARD_REDIS_ADDRESS:redis://10.102.105.231:6379}
spring.cache.type=redis
